### ISSUE TITLE
pro.opcode.bitrix.inspections.PhpIncludeInspection has to override getShortName()

### ISSUE THREAD

**Issue by artspb** [vizh/bxfs#5]
`getShortName()` has to be overridden to contain the same short name as specified in the `plugin.xml` (namely `BxPhpIncludeInspection`).

**Comment by vokamut** [comment]
`Short name not matched for class pro.opcode.bitrix.inspections.PhpIncludeInspection: getShortName() = PhpIncludeInspection; ep.shortName = BxPhpIncludeInspection`

**Comment by neuro159** [comment]
PhpStrorm team here...
We are still receiving these from customers.
Please address the issue, ask for assistance or plugin might get banned due to the volume of exceptions!

**Comment by vizh** [comment]
> PhpStrorm team here...
> We are still receiving these from customers.
> Please address the issue, ask for assistance or plugin might get banned due to the volume of exceptions!

It's too expensive to have IDEA Ultimate in Russia to just working on this extension. I recently reinstalled my OS and can take advantage of monthly trial. I will release an update to see if anyone else is using this plugin.

**Comment by vizh** [comment]
Uploaded 0.1.9 version of plugin to JetBrains Plugins Repository. Waiting for review.
